name: kd-fret
channels:
  - conda-forge
dependencies:
  - python=3.11
  - openjdk=11
  - numpy>=1.26
  - pandas>=2.1
  - matplotlib>=3.8
  - cellpose>=3.0
  - scikit-image>=0.22
  - tifffile>=2024.2
  - openpyxl>=3.1
  - pip
  - pip:
      - typer>=0.12
      - nd2>=0.10
      - pyimagej
      - roifile>=2026.2.10
